old/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('learnDjango.urls','learnDjango'),namespace = 'learnDjango')),
]

old/learnDjango/urls.py
from django.contrib import admin
from django.urls import path
from learnDjango import views
urlpatterns = [
    #path("{urlpath}",{view class}, name="{reverse indexing}")
    path('', views.Index.as_view(), name='index'),
    path('index', views.Index.as_view(), name='index'),
    path('login', views.Login_view.as_view(), name='login'),
    path('logout', views.Logout_view.as_view(), name='logout'),
    path('payment', views.Payment_view.as_view(), name='payment'),
    path('edit-room', views.EditRoom.as_view(), name='edit_room'),
    path('edit-person', views.EditPerson.as_view(), name='edit_person'),

]

old/learnDjango/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator,RegexValidator
from datetime import date

# Create your models here.

class BaseModel(models.Model):
    uid = models.AutoField(primary_key=True, editable=False, unique=True)
    created = models.DateField(auto_now_add = True)
    modified = models.DateField(auto_now= True)
    class Meta:
        abstract = True

class NepaliYear(BaseModel):
    year = models.DecimalField(decimal_places=0, default=2080,max_digits =4,validators=[MinValueValidator(2080),MaxValueValidator(3000)])
    current = models.BooleanField(default=True)    

class NepaliMonth(BaseModel):    
    month = models.CharField(max_length=20,default=" Unknown")
    def __str__(self):
        return self.month

class Room(BaseModel):
    roomName = models.CharField(max_length=20,default="none")
    floor = models.DecimalField(max_digits=1,decimal_places=0,default=0)
    occupied = models.BooleanField(default=False)
    rent = models.DecimalField(max_digits=6,decimal_places=2,validators=[MinValueValidator(0.00),MaxValueValidator(10000.00)],default=00.00)
    def __str__(self):
        return self.roomName

class Person(BaseModel):
    roomId = models.ForeignKey(Room,on_delete = models.CASCADE,default = 0)
    personName = models.CharField(max_length=50, default='unknown')
    phone = models.CharField(max_length=10,validators=[RegexValidator(r'^9[0-9]{9}$')])
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.personName

class RentHistory(BaseModel):
    roomId = models.ForeignKey(Room,on_delete = models.CASCADE,default = 0)
    personId = models.ForeignKey(Person,on_delete = models.CASCADE,default = 0)
    totalRequired = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(0.00),MaxValueValidator(999999.99)])
    totalRemaining = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(0.00),MaxValueValidator(999999.99)])
    def __str__(self):
        return self.remaining

class RentPayment(BaseModel):
    roomId = models.ForeignKey(Room,on_delete = models.CASCADE,default = 0)
    personId = models.ForeignKey(Person,on_delete = models.CASCADE,default = 0)
    RentHistoryId = models.ForeignKey(RentHistory,on_delete = models.CASCADE,default = 0)
    dateId = models.ForeignKey(NepaliYear,on_delete = models.CASCADE,default = 0)
    dateId = models.ForeignKey(NepaliMonth,on_delete = models.CASCADE,default = 0)
    paid = models.DecimalField(max_digits=6,decimal_places=2,validators=[MinValueValidator(0.00),MaxValueValidator(9999.99)])
    comment = models.CharField(max_length=100,default="No Comments")
    def __str__(self):
        return self.rentMonth

old/learnDjango/views.py
from django.shortcuts import render, redirect,HttpResponse
from django.views import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from learnDjango.models import *

class Index(View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request,'index.html')
        else:
            return redirect('/login')

class Login_view(View):
    def get(self,request):
        alert_title = request.session.get('alert_title',False)
        alert_detail = request.session.get('alert_detail',False)
        if(alert_title):del(request.session['alert_title'])
        if(alert_detail):del(request.session['alert_detail'])
        context = {'alert_title':alert_title,
            'alert_detail':alert_detail,}
        return render(request,"login.html",context)
    
    def post(self,request):
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username = username, password = password)
        if user is not None:# checks if the user is logged in or not?
            login(request,user) #logins the user
            return redirect ('/')
        else:
            request.session['alert_title'] = "Invalid Login Attempt"
            request.session['alert_detail'] = "Please enter valid login credential."
            return redirect(request.path)
class Logout_view(View):
    def get(self,request):
        request.session.clear()
        logout(request)
        return redirect('/')

class Payment_view(View):
    def get(self,request):
        year = NepaliYear.objects.filter(current = True)
        month = NepaliMonth.objects.all()
        room = Room.objects.filter(occupied = True)
        context = {
            "year" : year,
            "month": month,
            "room" : room,
        }
        return render(request,"payment.html",context)
    def post(self, request):
        return redirect('/payment')
    
class EditRoom(View):
    def get(self,request):
        room = Room.objects.all()
        context = {
            "room": room,
        }
        return render(request,"editRoom.html",context)
    def post(self, request):
        return redirect('/room-person')
    
class EditPerson(View):
    def get(self,request):
        person = Person.objects.all()
        context = {
            "person": person,
        }
        return render(request,"editPerson.html",context)
    def post(self, request):
        return redirect('/edit-person')
# class AuthView(View):
#     template_name = 'auth.html'

#     def get(self, request):
#         signup_form = UserCreationForm()#these are builtin forms from css
#         login_form = UserCreationForm()
#         return render(request, self.template_name, {'signup_form': signup_form, 'login_form': login_form})

#     def post(self, request):
#         if 'signup' in request.POST:
#             signup_form = UserCreationForm(request.POST)
#             login_form = AuthenticationForm()
#             if signup_form.is_valid():
#                 signup_form.save()
#                 return redirect('login')
#         elif 'login' in request.POST:
#             signup_form = UserCreationForm()
#             login_form = AuthenticationForm(request, data=request.POST)
#             if login_form.is_valid():
#                 user = login_form.get_user()
#                 login(request, user)
#                 return redirect('home')  # redirect to your desired page
#         else:
#             signup_form = UserCreationForm()
#             login_form = AuthenticationForm()

#         return render(request, self.template_name, {'signup_form': signup_form, 'login_form': login_form})

old/templates/auth.html
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
  </head>
  <body>
    <h2>Login</h2>
    <form method="post">
      {% csrf_token %} {{ login_form.as_p }}
      <button type="submit" name="login">Login</button>
    </form>
  </body>
</html>

old/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="static/rentProject.css" />
    <title>{% block title %}{% endblock title %}myRent</title>
    {% block head %}{% endblock head %}
  </head>

  <body>
    {% if user.is_authenticated %}
    <div class="nav-all sticky-top">
      <ul class="nav nav-tabs">
        <li>
          <a class="navbar-brand" href="/">MyRent</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url "learnDjango:payment" %}>Payment</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url "learnDjango:edit_room" %}>Edit Room</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url "learnDjango:edit_person" %}>Edit Person</a>
        </li>
        <li class="nav-item">
          <a class="nav-link logged" href={% url "learnDjango:logout" %}>Logout</a>
        </li>
      </ul>
    </div>
    {% endif %} {% block body %}{% endblock body %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

old/templates/editPerson.html
{% extends "base.html" %} {% block title %}edit_person | {% endblock title %}
{%block body %}
<h1>This is person</h1>
{% endblock body %}

old/templates/editRoom.html
{% extends "base.html" %} {% block title %}edit_room | {% endblock title %}
{%block body %}
<h1>This is Room</h1>
{% endblock body %}

old/templates/index.html
{% extends "base.html" %} {% block title %}{% endblock title %} {% block body %}
<h1>hello world</h1>
<p>this is index page</p>
{% endblock body %}

old/templates/login.html
{% extends "base.html" %} {% block tittle %}login | {% endblock tittle %}
{%block body %}
<div class="form">
  {% if alert_title %}
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
      <path
        d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
      />
    </symbol>
  </svg>
  <div class="alert alert-danger d-flex align-items-center" role="alert">
    <svg
      class="alert_icon bi flex-shrink-0 me-2"
      role="img"
      aria-label="Danger:"
    >
      <use xlink:href="#exclamation-triangle-fill" />
    </svg>
    <div><strong>{{alert_title}}!</strong> {{alert_detail}}</div>
  </div>
  {% endif %}

  <div class="form_title">Login</div>
  <form action="login" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        aria-describedby="teztHelp"
        name="username"
        required
      />
      <div id="username" class="form-text">
        We'll never share your email with anyone else.
      </div>
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        required
      />
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1" />
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <div class="d-grid gap-2 col-6 mx-auto">
      <button type="submit" class="button btn btn-primary">Login</button>
    </div>
  </form>
</div>
{% endblock body %}

old/templates/payment.html
{% extends "base.html" %}
{% block title %}Payment | {% endblock title %}
{% block body %}
<div class = "form">
  <div class="form_title">Payment</div>
  <form action="payment" method="POST">
    {% csrf_token %}
    <div>
      <label for="room">Room</label>
      <select class="form-select form-select-lg mb-3" aria-label="Large select example" id="room">
        <option value = "room">---Select Room---</option>
        {% for room in room %}
          <option id ={{room.room}} value={{room.room}}>{{room.room}}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      {% for year in year %}
      <h4>Year: {{year.year}}</h4>
      {% endfor %}
    </div>
    <div>
      <label for="month">Month</label>
      <select class="form-select form-select-lg mb-3" aria-label="Large select example" id = "month" >
        <option value = "month">---Select Month---</option>
        {% for month in month %}
          <option id ={{month.month}} value={{month.month}}>{{month.month}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="payment" class="form-label">Recieved Amount</label>
      <input
        type="number"
        class="form-control"
        id="payment"
        name="payment"
        required
      />
    </div>
    <div class="d-grid gap-2 col-6 mx-auto">
      <button type="submit" class="button btn btn-primary">Add Record</button>
    </div>
  </form>
</div>
</div>
  {% endblock body %}